name: bliss_housekeeping_app
description: Ứng dụng nội bộ đa vai trò cho Chủ chi nhánh, Tạp vụ và QC Bliss Home.
publish_to: none
version: 1.0.10+11

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^10.3.1
  http: ^1.6.0
  image_picker: ^1.2.3
  geolocator: ^13.0.4
  mobile_scanner: ^7.3.0
  network_info_plus: ^5.0.3
  crypto: ^3.0.7
  uuid: ^4.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/branding/app_icon.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/branding/app_icon.png
  min_sdk_android: 24
  remove_alpha_ios: true
