# Generated by Django 6.0.1 on 2026-08-05 02:20

import django.db.models.deletion
import django.utils.timezone
import housekeeping.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("housekeeping", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChecklistItemDefinition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("key", models.CharField(max_length=80)),
                ("group_name", models.CharField(blank=True, max_length=100)),
                ("title", models.CharField(max_length=255)),
                ("item_type", models.CharField(default="CHECKBOX", max_length=20)),
                ("is_required", models.BooleanField(default=True)),
                ("required_photo_count", models.PositiveSmallIntegerField(default=0)),
                ("options", models.JSONField(blank=True, default=list)),
                ("validation_rules", models.JSONField(blank=True, default=dict)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "db_table": "housekeeping_checklist_definitions",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("notification_type", models.CharField(db_index=True, max_length=50)),
                ("title", models.CharField(max_length=200)),
                ("body", models.TextField()),
                ("object_type", models.CharField(blank=True, max_length=50)),
                ("object_id", models.CharField(blank=True, max_length=64)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "db_table": "housekeeping_notifications",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="NotificationRecipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("read_at", models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
            options={
                "db_table": "housekeeping_notification_recipients",
            },
        ),
        migrations.CreateModel(
            name="OfflineMutationReceipt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=80)),
                ("operation", models.CharField(max_length=60)),
                ("payload_hash", models.CharField(max_length=64)),
                ("request_payload", models.JSONField(blank=True, default=dict)),
                ("response_payload", models.JSONField(blank=True, default=dict)),
                ("base_version", models.PositiveIntegerField(blank=True, null=True)),
                ("result_version", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RECEIVED", "Đã nhận"),
                            ("SUCCEEDED", "Thành công"),
                            ("FAILED", "Thất bại"),
                            ("CONFLICT", "Xung đột"),
                        ],
                        db_index=True,
                        default="RECEIVED",
                        max_length=20,
                    ),
                ),
                ("error_code", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "housekeeping_offline_receipts",
            },
        ),
        migrations.CreateModel(
            name="OutboxEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("event_type", models.CharField(db_index=True, max_length=60)),
                ("aggregate_type", models.CharField(max_length=50)),
                ("aggregate_id", models.CharField(max_length=64)),
                ("deduplication_key", models.CharField(max_length=120, unique=True)),
                ("payload", models.JSONField(default=dict)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                (
                    "available_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("last_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "housekeeping_outbox_events",
                "ordering": ["available_at", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="QCFailedItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("reason_code", models.CharField(blank=True, max_length=50)),
                ("reason", models.TextField()),
                ("note", models.TextField(blank=True)),
                ("rework_required", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "housekeeping_qc_failed_items",
            },
        ),
        migrations.CreateModel(
            name="ReworkRound",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("round_number", models.PositiveSmallIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Chờ làm lại"),
                            ("IN_PROGRESS", "Đang làm lại"),
                            ("SENT_TO_QC", "Đã gửi QC"),
                            ("COMPLETED", "Hoàn tất"),
                            ("CANCELLED", "Đã hủy"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("failed_items_only", models.BooleanField(default=True)),
                ("checklist_snapshot", models.JSONField(blank=True, default=list)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("sent_to_qc_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "housekeeping_rework_rounds",
                "ordering": ["round_number"],
            },
        ),
        migrations.CreateModel(
            name="ShiftAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_overtime", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "housekeeping_shift_assignments",
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=40)),
                ("name", models.CharField(max_length=120)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "housekeeping_skills",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SLAEscalationEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("event_type", models.CharField(max_length=40)),
                ("threshold_minutes", models.PositiveIntegerField(default=0)),
                ("recipient_role", models.CharField(max_length=32)),
                (
                    "occurred_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("payload", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "housekeeping_sla_escalations",
            },
        ),
        migrations.CreateModel(
            name="SLAPolicy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "task_type",
                    models.CharField(blank=True, db_index=True, max_length=30),
                ),
                (
                    "priority",
                    models.CharField(blank=True, db_index=True, max_length=10),
                ),
                ("acceptance_minutes", models.PositiveIntegerField(default=5)),
                ("start_minutes", models.PositiveIntegerField(default=15)),
                ("completion_minutes", models.PositiveIntegerField(default=45)),
                (
                    "checkin_risk_buffer_minutes",
                    models.PositiveIntegerField(default=15),
                ),
                ("exclude_approved_pause_time", models.BooleanField(default=True)),
                (
                    "escalation_minutes",
                    models.JSONField(
                        default=housekeeping.models.default_escalation_minutes
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "housekeeping_sla_policies",
                "ordering": ["branch__name", "name"],
            },
        ),
        migrations.CreateModel(
            name="SupplyLocation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=40)),
                ("name", models.CharField(max_length=150)),
                (
                    "notification_role",
                    models.CharField(default="warehouse", max_length=32),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "housekeeping_supply_locations",
                "ordering": ["branch__name", "name"],
            },
        ),
        migrations.CreateModel(
            name="TaskAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Chờ nhận"),
                            ("ACCEPTED", "Đã nhận"),
                            ("REJECTED", "Đã từ chối"),
                            ("RETURNED", "Đã trả"),
                            ("REASSIGNED", "Đã điều chuyển"),
                            ("ENDED", "Đã kết thúc"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("is_current", models.BooleanField(db_index=True, default=True)),
                ("reason_code", models.CharField(blank=True, max_length=50)),
                ("note", models.TextField(blank=True)),
                (
                    "assigned_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "housekeeping_task_assignments",
                "ordering": ["assigned_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="TaskHandover",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                (
                    "reconfirm_required_items",
                    models.JSONField(blank=True, default=list),
                ),
                ("handed_over_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "housekeeping_task_handovers",
                "ordering": ["handed_over_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="TaskRoomVerification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("QR_CODE", "QR phòng"),
                            ("GPS", "GPS"),
                            ("WIFI", "Wi-Fi"),
                            ("CAMERA", "Ảnh camera"),
                            ("MANAGER_OVERRIDE", "Quản lý xác nhận"),
                        ],
                        max_length=30,
                    ),
                ),
                ("submitted_value_hash", models.CharField(blank=True, max_length=128)),
                ("server_reference", models.CharField(blank=True, max_length=255)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "accuracy_meters",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("wifi_identifier", models.CharField(blank=True, max_length=255)),
                ("guest_consent_confirmed", models.BooleanField(default=False)),
                ("guest_consent_note", models.TextField(blank=True)),
                ("device_id", models.CharField(blank=True, max_length=255)),
                ("successful", models.BooleanField(db_index=True, default=False)),
                ("failure_reason", models.CharField(blank=True, max_length=255)),
                (
                    "verified_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
            ],
            options={
                "db_table": "housekeeping_room_verifications",
                "ordering": ["verified_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="TaskSLAState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("policy_snapshot", models.JSONField(blank=True, default=dict)),
                (
                    "acceptance_due_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "start_due_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "completion_due_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("excluded_pause_seconds", models.PositiveIntegerField(default=0)),
                ("acceptance_breached_at", models.DateTimeField(blank=True, null=True)),
                ("start_breached_at", models.DateTimeField(blank=True, null=True)),
                ("completion_breached_at", models.DateTimeField(blank=True, null=True)),
                ("checkin_risk_at", models.DateTimeField(blank=True, null=True)),
                ("last_evaluated_at", models.DateTimeField(blank=True, null=True)),
                ("legacy_backfill", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "housekeeping_task_sla_states",
            },
        ),
        migrations.AddField(
            model_name="branchmembership",
            name="membership_role",
            field=models.CharField(
                choices=[
                    ("HOUSEKEEPER", "Housekeeping"),
                    ("HOUSEKEEPING_LEAD", "Trưởng nhóm Housekeeping"),
                    ("MANAGER", "Quản lý"),
                    ("QC", "QC"),
                    ("WAREHOUSE", "Kho"),
                    ("TECHNICIAN", "Kỹ thuật"),
                    ("VIEWER", "Chỉ xem"),
                ],
                db_index=True,
                default="HOUSEKEEPER",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="housekeepingactivitylog",
            name="correlation_id",
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name="housekeepingactivitylog",
            name="idempotency_key",
            field=models.CharField(blank=True, db_index=True, max_length=80),
        ),
        migrations.AddField(
            model_name="housekeepingactivitylog",
            name="reason_code",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="housekeepingtask",
            name="acceptance_due_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="housekeepingtask",
            name="assigned_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_housekeeping_tasks_by_me",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="housekeepingtask",
            name="cancellation_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="housekeepingtask",
            name="cancelled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="housekeepingtask",
            name="cancelled_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cancelled_housekeeping_tasks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="housekeepingtask",
            name="current_rework_round",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="housekeepingtask",
            name="last_progress_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="housekeepingtask",
            name="rework_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="housekeepingtask",
            name="standard_duration_minutes",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="housekeepingtask",
            name="start_due_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="housekeepingtask",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_housekeeping_tasks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="issueticket",
            name="assigned_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="issueticket",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_housekeeping_issues",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="issueticket",
            name="resolution_note",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="issueticket",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resolved_housekeeping_issues",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="issueticket",
            name="version",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="qctask",
            name="checklist_snapshot",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="qctask",
            name="deadline_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="qctask",
            name="result_snapshot",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="room",
            name="allowed_wifi_identifiers",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="room",
            name="is_guest_occupied",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="room",
            name="is_locked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="room",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=7, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=7, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="operational_note",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="room",
            name="qr_identifier_hash",
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
        migrations.AddField(
            model_name="room",
            name="verification_radius_meters",
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name="supplyrequest",
            name="acknowledged_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="supplyrequest",
            name="blocks_completion",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="supplyrequest",
            name="resolution_note",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="supplyrequest",
            name="resolved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="supplyrequest",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resolved_supply_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="supplyrequest",
            name="version",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="taskchecklistitem",
            name="failure_accepted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="taskchecklistitem",
            name="failure_accepted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="accepted_checklist_failures",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="taskchecklistitem",
            name="failure_issue",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resolved_checklist_failures",
                to="housekeeping.issueticket",
            ),
        ),
        migrations.AddField(
            model_name="taskchecklistitem",
            name="failure_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="taskchecklistitem",
            name="options_snapshot",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="taskchecklistitem",
            name="update_version",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="taskchecklistitem",
            name="validation_snapshot",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="taskpause",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="taskpause",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_task_pauses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="taskpause",
            name="excluded_from_sla",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="taskpause",
            name="previous_status",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="taskphoto",
            name="accuracy_meters",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
        migrations.AddField(
            model_name="taskphoto",
            name="captured_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="taskphoto",
            name="checksum",
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name="taskphoto",
            name="device_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="taskphoto",
            name="issue",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="photos",
                to="housekeeping.issueticket",
            ),
        ),
        migrations.AddField(
            model_name="taskphoto",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=7, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="taskphoto",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=7, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="taskphoto",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="taskphoto",
            name="qc_round",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="photos",
                to="housekeeping.qctask",
            ),
        ),
        migrations.AddField(
            model_name="taskphoto",
            name="room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="housekeeping_photos",
                to="housekeeping.room",
            ),
        ),
        migrations.AddField(
            model_name="taskphoto",
            name="source",
            field=models.CharField(
                choices=[
                    ("CAMERA", "Camera"),
                    ("GALLERY", "Thư viện"),
                    ("OFFLINE_CAMERA", "Camera ngoại tuyến"),
                ],
                default="CAMERA",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="taskphoto",
            name="supply_request",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="photos",
                to="housekeeping.supplyrequest",
            ),
        ),
        migrations.AddField(
            model_name="taskphoto",
            name="sync_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Chờ đồng bộ"),
                    ("SYNCED", "Đã đồng bộ"),
                    ("FAILED", "Đồng bộ lỗi"),
                    ("CONFLICT", "Xung đột"),
                ],
                db_index=True,
                default="SYNCED",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="taskstatushistory",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="taskstatushistory",
            name="task_version",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="issueticket",
            name="status",
            field=models.CharField(
                choices=[
                    ("OPEN", "Đang mở"),
                    ("ASSIGNED", "Đã phân công"),
                    ("IN_PROGRESS", "Đang xử lý"),
                    ("RESOLVED", "Đã xử lý"),
                    ("CANCELLED", "Đã hủy"),
                ],
                default="OPEN",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="supplyrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Chờ xử lý"),
                    ("ACKNOWLEDGED", "Đã tiếp nhận"),
                    ("FULFILLED", "Đã cấp"),
                    ("REJECTED", "Từ chối"),
                    ("CANCELLED", "Đã hủy"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="taskphoto",
            name="category",
            field=models.CharField(
                choices=[
                    ("BEFORE", "Trước khi dọn"),
                    ("AFTER", "Sau khi dọn"),
                    ("ISSUE", "Sự cố"),
                    ("SUPPLY", "Thiếu vật tư"),
                    ("QC", "QC"),
                    ("AREA", "Khu vực"),
                    ("EVIDENCE", "Bằng chứng hoàn thành"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Area",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=40)),
                ("name", models.CharField(max_length=120)),
                ("floor_label", models.CharField(blank=True, max_length=80)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="areas",
                        to="housekeeping.branch",
                    ),
                ),
            ],
            options={
                "db_table": "housekeeping_areas",
                "ordering": ["branch__name", "name"],
            },
        ),
        migrations.AddField(
            model_name="branchmembership",
            name="areas",
            field=models.ManyToManyField(
                blank=True, related_name="memberships", to="housekeeping.area"
            ),
        ),
        migrations.AddField(
            model_name="housekeepingtask",
            name="area",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks",
                to="housekeeping.area",
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="area_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rooms",
                to="housekeeping.area",
            ),
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("BOOKED", "Đã đặt"),
                            ("CHECKED_IN", "Đã nhận phòng"),
                            ("CHECKED_OUT", "Đã trả phòng"),
                            ("CANCELLED", "Đã hủy"),
                        ],
                        db_index=True,
                        default="BOOKED",
                        max_length=20,
                    ),
                ),
                (
                    "checkin_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "checkout_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("guest_name", models.CharField(blank=True, max_length=200)),
                ("guest_phone", models.CharField(blank=True, max_length=30)),
                ("guest_count", models.PositiveSmallIntegerField(default=1)),
                ("special_requests", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to="housekeeping.branch",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to="housekeeping.room",
                    ),
                ),
            ],
            options={
                "db_table": "housekeeping_bookings",
                "ordering": ["-checkin_at", "code"],
            },
        ),
        migrations.AddField(
            model_name="housekeepingtask",
            name="booking",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="housekeeping_tasks",
                to="housekeeping.booking",
            ),
        ),
        migrations.AddField(
            model_name="issueticket",
            name="booking",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="issues",
                to="housekeeping.booking",
            ),
        ),
        migrations.CreateModel(
            name="BranchHousekeepingPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("allow_work_outside_shift", models.BooleanField(default=False)),
                ("allow_return_after_start", models.BooleanField(default=False)),
                ("allow_parallel_room_tasks", models.BooleanField(default=False)),
                ("require_guest_consent", models.BooleanField(default=True)),
                ("require_qr_verification", models.BooleanField(default=False)),
                ("require_gps_verification", models.BooleanField(default=False)),
                ("require_wifi_verification", models.BooleanField(default=False)),
                (
                    "block_completion_with_pending_sync",
                    models.BooleanField(default=True),
                ),
                (
                    "block_completion_with_pending_supply",
                    models.BooleanField(default=True),
                ),
                ("rework_failed_items_only", models.BooleanField(default=True)),
                ("concurrent_task_limit", models.PositiveSmallIntegerField(default=3)),
                (
                    "checkin_risk_buffer_minutes",
                    models.PositiveSmallIntegerField(default=15),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "branch",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="housekeeping_policy",
                        to="housekeeping.branch",
                    ),
                ),
            ],
            options={
                "db_table": "housekeeping_branch_policies",
            },
        ),
        migrations.AddField(
            model_name="taskchecklistitem",
            name="definition",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="task_snapshots",
                to="housekeeping.checklistitemdefinition",
            ),
        ),
        migrations.CreateModel(
            name="ChecklistTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=80)),
                ("name", models.CharField(max_length=180)),
                (
                    "task_type",
                    models.CharField(blank=True, db_index=True, max_length=30),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checklist_templates",
                        to="housekeeping.branch",
                    ),
                ),
            ],
            options={
                "db_table": "housekeeping_checklist_templates",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ChecklistVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version_number", models.PositiveIntegerField(default=1)),
                ("version_label", models.CharField(default="v1", max_length=30)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Nháp"),
                            ("PUBLISHED", "Đã phát hành"),
                            ("RETIRED", "Ngừng sử dụng"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("policy_snapshot", models.JSONField(blank=True, default=dict)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_housekeeping_checklist_versions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="housekeeping.checklisttemplate",
                    ),
                ),
            ],
            options={
                "db_table": "housekeeping_checklist_versions",
                "ordering": ["template", "version_number"],
            },
        ),
        migrations.AddField(
            model_name="checklistitemdefinition",
            name="version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="item_definitions",
                to="housekeeping.checklistversion",
            ),
        ),
        migrations.AddField(
            model_name="housekeepingtask",
            name="checklist_template_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tasks",
                to="housekeeping.checklistversion",
            ),
        ),
        migrations.CreateModel(
            name="HousekeepingTeam",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=40)),
                ("name", models.CharField(max_length=120)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "areas",
                    models.ManyToManyField(
                        blank=True, related_name="teams", to="housekeeping.area"
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="housekeeping_teams",
                        to="housekeeping.branch",
                    ),
                ),
                (
                    "leader",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="led_housekeeping_teams",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "housekeeping_teams",
                "ordering": ["branch__name", "name"],
            },
        ),
        migrations.AddField(
            model_name="branchmembership",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="memberships",
                to="housekeeping.housekeepingteam",
            ),
        ),
        migrations.AddField(
            model_name="housekeepingtask",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks",
                to="housekeeping.housekeepingteam",
            ),
        ),
        migrations.AddIndex(
            model_name="housekeepingtask",
            index=models.Index(
                fields=["shift", "status", "scheduled_start_at"],
                name="hk_shift_status_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="housekeepingtask",
            index=models.Index(
                fields=["assignee", "status", "due_at"], name="hk_assignee_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="housekeepingtask",
            index=models.Index(fields=["room", "status"], name="hk_room_status_idx"),
        ),
        migrations.AddField(
            model_name="notification",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="housekeeping.branch",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="housekeeping.housekeepingtask",
            ),
        ),
        migrations.AddField(
            model_name="notificationrecipient",
            name="notification",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipient_rows",
                to="housekeeping.notification",
            ),
        ),
        migrations.AddField(
            model_name="notificationrecipient",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="housekeeping_notifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="offlinemutationreceipt",
            name="task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="offline_receipts",
                to="housekeeping.housekeepingtask",
            ),
        ),
        migrations.AddField(
            model_name="offlinemutationreceipt",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="offline_mutation_receipts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="qcfaileditem",
            name="checklist_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="qc_failures",
                to="housekeeping.taskchecklistitem",
            ),
        ),
        migrations.AddField(
            model_name="qcfaileditem",
            name="qc_round",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="failed_items",
                to="housekeeping.qctask",
            ),
        ),
        migrations.AddField(
            model_name="reworkround",
            name="source_qc_round",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rework_rounds",
                to="housekeeping.qctask",
            ),
        ),
        migrations.AddField(
            model_name="reworkround",
            name="started_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="started_housekeeping_reworks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="reworkround",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rework_rounds",
                to="housekeeping.housekeepingtask",
            ),
        ),
        migrations.AddField(
            model_name="qcfaileditem",
            name="resolved_in_rework",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resolved_failed_items",
                to="housekeeping.reworkround",
            ),
        ),
        migrations.AddField(
            model_name="shiftassignment",
            name="areas",
            field=models.ManyToManyField(
                blank=True, related_name="shift_assignments", to="housekeeping.area"
            ),
        ),
        migrations.AddField(
            model_name="shiftassignment",
            name="assigned_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_housekeeping_shift_assignments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="shiftassignment",
            name="shift",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="housekeeping.shift",
            ),
        ),
        migrations.AddField(
            model_name="shiftassignment",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shift_assignments",
                to="housekeeping.housekeepingteam",
            ),
        ),
        migrations.AddField(
            model_name="shiftassignment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="housekeeping_shift_assignments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="skill",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="housekeeping_skills",
                to="housekeeping.branch",
            ),
        ),
        migrations.AddField(
            model_name="housekeepingteam",
            name="required_skills",
            field=models.ManyToManyField(
                blank=True, related_name="teams", to="housekeeping.skill"
            ),
        ),
        migrations.AddField(
            model_name="branchmembership",
            name="skills",
            field=models.ManyToManyField(
                blank=True, related_name="memberships", to="housekeeping.skill"
            ),
        ),
        migrations.AddField(
            model_name="slaescalationevent",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sla_escalations",
                to="housekeeping.housekeepingtask",
            ),
        ),
        migrations.AddField(
            model_name="slapolicy",
            name="branch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sla_policies",
                to="housekeeping.branch",
            ),
        ),
        migrations.AddField(
            model_name="supplylocation",
            name="branch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="supply_locations",
                to="housekeeping.branch",
            ),
        ),
        migrations.AddField(
            model_name="supplyrequest",
            name="destination",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="requests",
                to="housekeeping.supplylocation",
            ),
        ),
        migrations.AddField(
            model_name="taskassignment",
            name="assigned_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="housekeeping_assignments_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="taskassignment",
            name="assignee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="housekeeping_assignments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="taskassignment",
            name="shift",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="task_assignments",
                to="housekeeping.shift",
            ),
        ),
        migrations.AddField(
            model_name="taskassignment",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="housekeeping.housekeepingtask",
            ),
        ),
        migrations.AddField(
            model_name="taskassignment",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="task_assignments",
                to="housekeeping.housekeepingteam",
            ),
        ),
        migrations.AddField(
            model_name="taskhandover",
            name="from_assignment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="outgoing_handovers",
                to="housekeeping.taskassignment",
            ),
        ),
        migrations.AddField(
            model_name="taskhandover",
            name="from_shift",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="outgoing_handovers",
                to="housekeeping.shift",
            ),
        ),
        migrations.AddField(
            model_name="taskhandover",
            name="from_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="housekeeping_handovers_sent",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="taskhandover",
            name="handed_over_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="housekeeping_handovers_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="taskhandover",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="handovers",
                to="housekeeping.housekeepingtask",
            ),
        ),
        migrations.AddField(
            model_name="taskhandover",
            name="to_assignment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="incoming_handovers",
                to="housekeeping.taskassignment",
            ),
        ),
        migrations.AddField(
            model_name="taskhandover",
            name="to_shift",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="incoming_handovers",
                to="housekeeping.shift",
            ),
        ),
        migrations.AddField(
            model_name="taskhandover",
            name="to_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="housekeeping_handovers_received",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="taskroomverification",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="room_verifications",
                to="housekeeping.housekeepingtask",
            ),
        ),
        migrations.AddField(
            model_name="taskroomverification",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="room_verifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="taskslastate",
            name="policy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="task_states",
                to="housekeeping.slapolicy",
            ),
        ),
        migrations.AddField(
            model_name="taskslastate",
            name="task",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sla_state",
                to="housekeeping.housekeepingtask",
            ),
        ),
        migrations.AddConstraint(
            model_name="area",
            constraint=models.UniqueConstraint(
                fields=("branch", "code"), name="unique_branch_area_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.UniqueConstraint(
                fields=("branch", "code"), name="unique_branch_booking_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="checklisttemplate",
            constraint=models.UniqueConstraint(
                fields=("branch", "code"), name="unique_branch_checklist_tpl"
            ),
        ),
        migrations.AddConstraint(
            model_name="checklistversion",
            constraint=models.UniqueConstraint(
                fields=("template", "version_number"),
                name="unique_checklist_tpl_number",
            ),
        ),
        migrations.AddConstraint(
            model_name="checklistversion",
            constraint=models.UniqueConstraint(
                fields=("template", "version_label"), name="unique_checklist_tpl_label"
            ),
        ),
        migrations.AddConstraint(
            model_name="checklistitemdefinition",
            constraint=models.UniqueConstraint(
                fields=("version", "key"), name="unique_checklist_version_key"
            ),
        ),
        migrations.AddIndex(
            model_name="notificationrecipient",
            index=models.Index(fields=["user", "read_at"], name="hk_notice_user_idx"),
        ),
        migrations.AddConstraint(
            model_name="notificationrecipient",
            constraint=models.UniqueConstraint(
                fields=("notification", "user"), name="unique_notification_user"
            ),
        ),
        migrations.AddIndex(
            model_name="offlinemutationreceipt",
            index=models.Index(
                fields=["task", "status", "created_at"], name="hk_receipt_task_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="offlinemutationreceipt",
            constraint=models.UniqueConstraint(
                fields=("user", "idempotency_key"), name="unique_user_idempotency_key"
            ),
        ),
        migrations.AddConstraint(
            model_name="reworkround",
            constraint=models.UniqueConstraint(
                fields=("task", "round_number"), name="unique_task_rework_round"
            ),
        ),
        migrations.AddConstraint(
            model_name="qcfaileditem",
            constraint=models.UniqueConstraint(
                fields=("qc_round", "checklist_item"), name="unique_qc_failed_item"
            ),
        ),
        migrations.AddConstraint(
            model_name="shiftassignment",
            constraint=models.UniqueConstraint(
                fields=("user", "shift"), name="unique_user_shift_assignment"
            ),
        ),
        migrations.AddConstraint(
            model_name="skill",
            constraint=models.UniqueConstraint(
                fields=("branch", "code"), name="unique_branch_skill_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="housekeepingteam",
            constraint=models.UniqueConstraint(
                fields=("branch", "code"), name="unique_branch_team_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="slaescalationevent",
            constraint=models.UniqueConstraint(
                fields=("task", "event_type", "threshold_minutes", "recipient_role"),
                name="unique_task_sla_escalation",
            ),
        ),
        migrations.AddConstraint(
            model_name="supplylocation",
            constraint=models.UniqueConstraint(
                fields=("branch", "code"), name="unique_branch_supply_loc"
            ),
        ),
        migrations.AddIndex(
            model_name="taskassignment",
            index=models.Index(
                fields=["assignee", "is_current", "status"], name="hk_assign_user_idx"
            ),
        ),
    ]
