# Generated by Django 6.0.1 on 2026-08-05 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("housekeeping", "0003_backfill_domain_foundation"),
    ]

    operations = [
        migrations.AddField(
            model_name="branchhousekeepingpolicy",
            name="require_camera_verification",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="branchhousekeepingpolicy",
            name="require_direct_camera_for_evidence",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="taskroomverification",
            name="method",
            field=models.CharField(
                choices=[
                    ("QR_CODE", "QR phòng"),
                    ("GPS", "GPS"),
                    ("WIFI", "Wi-Fi"),
                    ("CAMERA", "Ảnh camera"),
                    ("MANAGER_OVERRIDE", "Quản lý xác nhận"),
                    ("GUEST_CONSENT", "Khách đồng ý"),
                ],
                max_length=30,
            ),
        ),
    ]
