# Generated by Django 6.0.1 on 2026-08-07.

import uuid

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


def backfill_open_issue_blockers(apps, schema_editor):
    IssueTicket = apps.get_model("housekeeping", "IssueTicket")
    RoomBlocker = apps.get_model("room_operations", "RoomBlocker")
    terminal_statuses = {"RESOLVED", "CANCELLED"}
    RoomBlocker.objects.bulk_create(
        [
            RoomBlocker(
                branch_id=issue.task.branch_id,
                room_id=issue.room_id,
                issue_id=issue.id,
                kind="ISSUE",
                status="ACTIVE",
                reason=issue.description[:500],
                starts_at=issue.created_at,
                version=1,
                created_by_id=issue.reported_by_id,
            )
            for issue in IssueTicket.objects.filter(blocks_room_ready=True)
            .exclude(status__in=terminal_statuses)
            .select_related("task")
            .iterator()
        ]
    )


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("housekeeping", "0014_structured_booking_requests"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RoomBlocker",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("kind", models.CharField(choices=[("ISSUE", "Sự cố"), ("MAINTENANCE", "Bảo trì"), ("CLEANLINESS", "Vệ sinh"), ("SAFETY", "An toàn"), ("MANUAL", "Quản lý chặn thủ công"), ("OTHER", "Lý do khác")], db_index=True, max_length=20)),
                ("status", models.CharField(choices=[("ACTIVE", "Đang chặn"), ("CLEARANCE_PENDING", "Chờ xác nhận gỡ chặn"), ("CLEARED", "Đã gỡ chặn"), ("CANCELLED", "Đã hủy")], db_index=True, default="ACTIVE", max_length=24)),
                ("reason", models.CharField(max_length=500)),
                ("starts_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("planned_end_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("clearance_requested_at", models.DateTimeField(blank=True, null=True)),
                ("clearance_note", models.TextField(blank=True)),
                ("cleared_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("branch", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="room_blockers", to="housekeeping.branch")),
                ("clearance_requested_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="requested_room_blocker_clearances", to=settings.AUTH_USER_MODEL)),
                ("cleared_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="cleared_room_blockers", to=settings.AUTH_USER_MODEL)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_room_blockers", to=settings.AUTH_USER_MODEL)),
                ("issue", models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="room_blocker", to="housekeeping.issueticket")),
                ("room", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="operational_blockers", to="housekeeping.room")),
            ],
            options={"db_table": "room_operations_blockers", "ordering": ["-starts_at", "-created_at"]},
        ),
        migrations.CreateModel(
            name="RoomBlockerHistory",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("action", models.CharField(choices=[("CREATED", "Tạo blocker"), ("CLEARANCE_REQUESTED", "Yêu cầu gỡ blocker"), ("CLEARED", "Xác nhận gỡ blocker"), ("CANCELLED", "Hủy blocker")], db_index=True, max_length=24)),
                ("blocker_version", models.PositiveIntegerField()),
                ("note", models.TextField(blank=True)),
                ("before_snapshot", models.JSONField(blank=True, default=dict)),
                ("after_snapshot", models.JSONField(blank=True, default=dict)),
                ("correlation_id", models.CharField(blank=True, db_index=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("actor", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="room_blocker_history_entries", to=settings.AUTH_USER_MODEL)),
                ("blocker", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="history", to="room_operations.roomblocker")),
                ("branch", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="room_blocker_history", to="housekeeping.branch")),
            ],
            options={"db_table": "room_operations_blocker_history", "ordering": ["-created_at", "-id"]},
        ),
        migrations.CreateModel(
            name="RoomStopSell",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("reason_code", models.CharField(choices=[("MAINTENANCE", "Bảo trì hoặc sửa chữa"), ("SAFETY", "An toàn"), ("CLEANLINESS", "Vệ sinh chưa đạt"), ("OWNER_HOLD", "Chủ chi nhánh tạm giữ phòng"), ("GUEST_IMPACT", "Ảnh hưởng trải nghiệm khách"), ("OTHER", "Lý do khác")], db_index=True, max_length=24)),
                ("reason", models.CharField(max_length=500)),
                ("starts_at", models.DateTimeField(db_index=True)),
                ("planned_end_at", models.DateTimeField(db_index=True)),
                ("status", models.CharField(choices=[("ACTIVE", "Đang dừng bán"), ("REOPEN_REQUESTED", "Chờ xác nhận mở lại"), ("ENDED", "Đã mở bán lại"), ("CANCELLED", "Đã hủy")], db_index=True, default="ACTIVE", max_length=24)),
                ("version", models.PositiveIntegerField(default=1)),
                ("reopen_requested_at", models.DateTimeField(blank=True, null=True)),
                ("reopen_request_note", models.TextField(blank=True)),
                ("reopened_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("reopen_confirmation_note", models.TextField(blank=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancellation_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("blocker", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="stop_sells", to="room_operations.roomblocker")),
                ("branch", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="room_stop_sells", to="housekeeping.branch")),
                ("cancelled_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="cancelled_room_stop_sells", to=settings.AUTH_USER_MODEL)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_room_stop_sells", to=settings.AUTH_USER_MODEL)),
                ("reopen_requested_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="requested_room_reopens", to=settings.AUTH_USER_MODEL)),
                ("reopened_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="confirmed_room_reopens", to=settings.AUTH_USER_MODEL)),
                ("room", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="stop_sells", to="housekeeping.room")),
            ],
            options={"db_table": "room_operations_stop_sells", "ordering": ["-starts_at", "-created_at"]},
        ),
        migrations.CreateModel(
            name="RoomStopSellHistory",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("action", models.CharField(choices=[("CREATED", "Bắt đầu dừng bán"), ("REOPEN_REQUESTED", "Yêu cầu mở bán lại"), ("REOPEN_CONFIRMED", "Xác nhận mở bán lại"), ("CANCELLED", "Hủy lịch dừng bán")], db_index=True, max_length=24)),
                ("stop_sell_version", models.PositiveIntegerField()),
                ("note", models.TextField(blank=True)),
                ("before_snapshot", models.JSONField(blank=True, default=dict)),
                ("after_snapshot", models.JSONField(blank=True, default=dict)),
                ("correlation_id", models.CharField(blank=True, db_index=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("actor", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="room_stop_sell_history_entries", to=settings.AUTH_USER_MODEL)),
                ("branch", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="room_stop_sell_history", to="housekeeping.branch")),
                ("stop_sell", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="history", to="room_operations.roomstopsell")),
            ],
            options={"db_table": "room_operations_stop_sell_history", "ordering": ["-created_at", "-id"]},
        ),
        migrations.AddIndex(model_name="roomblocker", index=models.Index(fields=["branch", "status", "starts_at"], name="room_blocker_scope_idx")),
        migrations.AddIndex(model_name="roomblocker", index=models.Index(fields=["room", "status"], name="room_blocker_room_idx")),
        migrations.AddConstraint(model_name="roomblocker", constraint=models.CheckConstraint(check=models.Q(("planned_end_at__isnull", True), ("planned_end_at__gt", models.F("starts_at")), _connector="OR"), name="room_blocker_end_after_start")),
        migrations.AddConstraint(model_name="roomblockerhistory", constraint=models.UniqueConstraint(fields=("blocker", "blocker_version", "action"), name="unique_room_blocker_version_action")),
        migrations.AddIndex(model_name="roomstopsell", index=models.Index(fields=["branch", "status", "starts_at"], name="stop_sell_scope_idx")),
        migrations.AddIndex(model_name="roomstopsell", index=models.Index(fields=["room", "status", "starts_at"], name="stop_sell_room_idx")),
        migrations.AddConstraint(model_name="roomstopsell", constraint=models.CheckConstraint(check=models.Q(("planned_end_at__gt", models.F("starts_at"))), name="stop_sell_end_after_start")),
        migrations.AddConstraint(model_name="roomstopsellhistory", constraint=models.UniqueConstraint(fields=("stop_sell", "stop_sell_version", "action"), name="unique_stop_sell_version_action")),
        migrations.RunPython(backfill_open_issue_blockers, migrations.RunPython.noop),
    ]
